# Github-checker
# #noServerNovember

service: github-checker

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1

functions:
  checker:
    handler: handler.checker
    events: 
      - http: POST checker
